#!/bin/sh

TMP=`mktemp -d -t yt-dlp-XXXXXX`
DEST=/usr/local/bin/yt-dlp

#F=https://youtube-dl.org/downloads/latest/youtube-dl
F=https://github.com/yt-dlp/yt-dlp/releases/download/2024.04.09/yt-dlp

wget "$F" -O "$TMP/yt-dlp" || exit 1

test -s "$TMP/yt-dlp" || exit 2

test -s "$DEST" && mv -f -v "$DEST" "$TMP/yt-dlp.bak"

cp -v -f "$TMP/yt-dlp" "$DEST" || exit 3

chmod 755 "$DEST"

echo SUCCESS
