#!/bin/sh

TMP=`mktemp -d -t youtube-dl-XXXXXX`
DEST=/usr/local/bin/youtube-dl

wget https://youtube-dl.org/downloads/latest/youtube-dl -O "$TMP/youtube-dl" || exit 1

test -s "$TMP/youtube-dl" || exit 2

test -s "$DEST" && mv -f -v "$DEST" "$TMP/youtube-dl.bak"

cp -v -f "$TMP/youtube-dl" "$DEST" || exit 3

chmod 755 "$DEST"

echo SUCCESS
