#!/bin/sh

DATE=`date`

LOG=/run/shm/reconnect.log

IF=eth0

echo $DATE >> $LOG

#echo $DATE >> $LOG
if ping -q -c 3 comtrend >/dev/null
then
 echo OK >> $LOG
else
 echo reconnecting >> $LOG
 ifdown $IF >> $LOG

 sleep 3
 ifdown --force $IF >> $LOG

 sleep 10 
 ifup --force $IF >> $LOG
fi

