#!/bin/sh


if  ip  addr | grep -q " 10.0.4."
then
 # VPN
 exec /usr/bin/corkscrew "$@"
elif  ip  addr | grep -q " 10.50."
then
 # office eth
 exec /usr/bin/corkscrew "$@"
elif  ip  addr | grep -q " 172.17.2."
then
 # home
 exec nc banan 22
else
 # outside
 exec nc $3 $4
fi
